### ISSUE TITLE
Can this support FK relationships and graphs

### ISSUE THREAD

**Issue by weedkiller** [ren85/linqdb#1]
Hi, this is great I like the idea of the native object store and full search... about time!!!

- Can you include in the documentation how to maintain, edit/update Foreign keys, 
- how are inherited objects stored, I mean is there a [Table Per Hierarchy](https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-1-table-per-hierarchy-tph) concept here? TPF - 
- I also want to share some other db's out [there for ref](http://bit.ly/2kb7H4K)

Lastly a GUI or admin tool to manage/backup/restore/MD5 integrity would accelerate adoption!

thanks

**Comment by ren85** [comment]
Hello, thank you for feedback.

- Currently there is no real foreign keys, i.e. a foreign key is just a column without any constraints. This might be implemented in the future.
- No, there is no TPF
- There is currently only embedded version available, with one process able to access, so no GUI admin tool.

I'm currently working on a server version (which will be with same api) and then Visual Studio would be as admin tool and Fiddler as a profiler. 

Best regards,
ren

**Comment by weedkiller** [comment]
Awesome thanks! 💯
